---

- name: Set Umbrella DNS servers for IPv4 (PS)
  win_shell: "Set-DNSClientServerAddress -InterfaceIndex {{ item }} -ServerAddresses \"1.1.1.1,1.1.1.2\""
  loop: "{{ ps_interfaces.stdout_lines  }}"
  when: ansible_distribution_major_version|int >= 6
